### ISSUE TITLE
bug: Duplicate entries in the dataset.

### ISSUE THREAD

**Issue by mattramos** [lgouldsbrough/LancasterAQ#4]
# Bug Report

Initial version

**Current behavior:**

There are multiple repeated data points > 9000 out of 113000. These are identical row entries. They are also repeated in the initial csvs from the instrumentation.

**Expected behavior:**

There shouldn't be repeated data

**Steps to reproduce:**

```
import LancasterAQ as laq
laq.TabularObject().to_pandas().head(10)
```

In the printout (below) you can see that rows 2,3 and 4 are identical.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/33627791/193259104-a39c9973-8670-4cd2-a200-b94beeaacc5b.png">

**Comment by lgouldsbrough** [comment]
Issue is fixed in this merge #6.
