### ISSUE TITLE
bug: python versioning

### ISSUE THREAD

**Issue by mattramos** [lgouldsbrough/LancasterAQ#5]
# Bug Report

First version.

**Current behavior:**

On pip install 
"ERROR: Could not find a version that satisfies the requirement LancasterAQ (from versions: none)
ERROR: No matching distribution found for LancasterAQ". 

 Python 3.8.10 on Linux.
**Expected behavior:**

It to install

**Steps to reproduce:**

run on colab
```
!pip install LancasterAQ 
```

**Other information:**

See thread here
https://mobile.twitter.com/geospacedman/status/1577263654718042113

**Comment by mattramos** [comment]
Need to specify in the README that the python version needs to be >3.9

**Comment by lgouldsbrough** [comment]
Would be happy to accept a pull request of the package back-ported to Python 3.8.

Python version requirements are listed on PyPI. 
README.md has been updated to include a note about the python version requirements of Python >=3.9 to make it clearer.
